"""Load the cuRobo robot config dict for MotionGen.

The repo ships a fully-baked robot YAML (configs/robot_gen3_2f85.yaml,
generated by scripts/bake_robot_config.py) whose collision spheres already
carry RAMMP-Kinova's audit-tuned patches — the boosted arm spheres, the
18-sphere gripper shell, and the inflated fingertip pads. No sphere values
are patched in memory — the baked YAML is what plans; only retract_config is
re-applied from the configured home pose (a no-op for the baked file, and
the elbow-family fix for stock bundled configs).

The YAML's urdf_path/asset_root_path stay RELATIVE (robot/kinova/...): cuRobo
resolves them against its own installed content directory, so the URDF and
meshes are never vendored into this repo. Loading a stock bundled config by
bare name (e.g. 'kinova_gen3.yml') also works — spheres referenced as a
`spheres/*.yml` string are inlined the way cuRobo's own loader would.
"""

import yaml


def load_robot_config(path, home_pose_rad=None, joint_names=None):
    """Robot-config YAML -> the robot_cfg dict MotionGenConfig accepts.

    home_pose_rad + joint_names (controller order): when given, overwrite
    cspace retract_config with the home pose so IK seeds land in the same
    elbow family as the stack's home. The bundled retract lives in the
    OPPOSITE family — seeding there makes every crossing plan a huge,
    winding, wrist-twisting reconfiguration (RAMMP-Kinova field lesson).
    The baked YAML already carries the right retract; applying it again is
    a harmless no-op that also covers stock-config users.
    """
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)["robot_cfg"]
    kin = cfg["kinematics"]

    spheres = kin.get("collision_spheres")
    if isinstance(spheres, str):
        # Stock-style reference into cuRobo's own content tree.
        from curobo.util_file import get_robot_configs_path, join_path

        with open(join_path(get_robot_configs_path(), spheres), "r") as f:
            loaded = yaml.safe_load(f)
        kin["collision_spheres"] = loaded.get("collision_spheres", loaded)

    if home_pose_rad is not None and joint_names is not None:
        cspace = kin["cspace"]
        by_name = dict(zip(joint_names, home_pose_rad))
        cspace["retract_config"] = [float(by_name[n]) for n in cspace["joint_names"]]
    return cfg
