"""Load the cuRobo robot config dict for MotionGen.

The repo ships a fully-baked robot YAML (configs/robot_gen3_2f85.yaml,
generated by scripts/bake_robot_config.py) whose collision spheres already
carry RAMMP-Kinova's audit-tuned patches — the boosted arm spheres, the
18-sphere gripper shell, and the inflated fingertip pads. No sphere values
are patched in memory, and nothing is re-applied at load: the baked YAML is
what plans, retract_config (the IK seed) included.

The YAML's urdf_path/asset_root_path stay RELATIVE (robot/kinova/...): cuRobo
resolves them against its own installed content directory, so the URDF and
meshes are never vendored into this repo. Loading a stock bundled config by
bare name (e.g. 'kinova_gen3.yml') also works — spheres referenced as a
`spheres/*.yml` string are inlined the way cuRobo's own loader would.
"""

import yaml


def load_robot_config(path):
    """Robot-config YAML -> the robot_cfg dict MotionGenConfig accepts.

    retract_config comes from the YAML as-is. It is the IK seed, and the
    baked file (scripts/bake_robot_config.py) is what puts it in the right
    elbow family — cuRobo's BUNDLED Gen3 retract lives in the OPPOSITE
    family, and seeding there makes every crossing plan a huge, winding,
    wrist-twisting reconfiguration (RAMMP-Kinova field lesson). Load a
    stock config by bare name and you inherit that bad seed; bake instead.

    Nothing here rewrites the seed at load time. The planner holds no pose
    of its own to rewrite it with — where the arm belongs is the arm
    layer's business, not the planner's (issue #6).
    """
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)["robot_cfg"]
    kin = cfg["kinematics"]

    spheres = kin.get("collision_spheres")
    if isinstance(spheres, str):
        # Stock-style reference into cuRobo's own content tree.
        from curobo.util_file import get_robot_configs_path, join_path

        with open(join_path(get_robot_configs_path(), spheres), "r") as f:
            loaded = yaml.safe_load(f)
        kin["collision_spheres"] = loaded.get("collision_spheres", loaded)

    return cfg
