#!/usr/bin/env python3
"""Bake the arm's SELF-MODEL for the cameras node.

    python3 scripts/bake_self_model.py

Writes core/rammp_curobo/configs/self_model_gen3_2f85.yaml: cuRobo's own
collision spheres, keyed by the TF frame each set rides on, so the depth
pipeline can erase the arm from the obstacle map with the same geometry
the planner collides against — instead of nine fat capsules that had to
be 25 cm wide to cover the gripper.

Arm links keep cuRobo's link frames: verified identical to ros2_kortex's
URDF for all eight joints (origin, rpy, axis, parent/child). The gripper
is re-expressed in end_effector_link, because the two URDFs attach it
with a different yaw (+90 deg in cuRobo's) and different link names.

Regenerate after ANY change to robot_gen3_2f85.yaml. Never hand-edit.
"""

import os
import sys

import numpy as np
import yaml

from rammp_curobo import CuRoboPlanner
from rammp_curobo.config import resolve_config

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "core", "rammp_curobo", "configs", "self_model_gen3_2f85.yaml",
)
ARM = ["base_link", "shoulder_link", "half_arm_1_link", "half_arm_2_link",
       "forearm_link", "spherical_wrist_1_link", "spherical_wrist_2_link",
       "bracelet_link"]
TOOL_AHEAD_OF_EE = 0.120            # tool_frame = end_effector_link + 0.120 z


def quat_wxyz_to_mat(w, x, y, z):
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


def main():
    pl = CuRoboPlanner.from_config("gen3_real.yaml", planner_overrides={"warmup": False})
    robot_yaml = resolve_config(pl._cfg["robot"], relative_to=pl._config_dir)
    with open(robot_yaml) as f:
        kin = yaml.safe_load(f)["robot_cfg"]["kinematics"]
    by_link = kin["collision_spheres"]
    # cuRobo inflates every sphere by collision_sphere_buffer at load; the
    # self-model must be what the planner actually collides against
    buffer = float(kin.get("collision_sphere_buffer", 0.0))
    model = {}
    for link in ARM:
        rows = [[s["center"][0], s["center"][1], s["center"][2], s["radius"] + buffer]
                for s in by_link[link]]
        model[link] = rows

    # gripper: every sphere cuRobo hangs past the wrist, in ee frame, from
    # FK — and checked rigid across three very different arm poses
    idx_map = pl._motion_gen.kinematics.kinematics_config.link_sphere_idx_map
    idx_map = idx_map.detach().cpu().numpy()
    n_arm = sum(len(by_link[link]) for link in ARM)
    poses = [list(pl.home_pose)]
    for deltas in (((1, 0.6), (3, 0.5), (5, -0.4)), ((0, -0.8), (2, 0.3), (6, 1.0))):
        q = list(pl.home_pose)
        for j, dv in deltas:
            q[j] += dv
        poses.append(q)
    in_ee = []
    for q in poses:
        sph = pl.link_spheres(q)
        p_tool, q_wxyz = pl.fk(q, quat_order="wxyz")
        r = quat_wxyz_to_mat(*q_wxyz)
        p_ee = np.asarray(p_tool) - r @ np.array([0.0, 0.0, TOOL_AHEAD_OF_EE])
        grip = sph[n_arm:]
        in_ee.append(np.column_stack([(grip[:, :3] - p_ee) @ r, grip[:, 3]]))
    spread = max(float(np.abs(in_ee[i] - in_ee[0]).max()) for i in range(1, len(in_ee)))
    if spread > 1e-3:
        sys.exit("gripper spheres are not rigid in end_effector_link (spread %.4f m) "
                 "— the sphere->link bookkeeping changed; do not write" % spread)
    model["end_effector_link"] = [[float(v) for v in row] for row in in_ee[0]]
    total = sum(len(v) for v in model.values())
    if total != len(pl.link_spheres(pl.home_pose)):
        sys.exit("sphere count %d != cuRobo's %d" % (total, len(pl.link_spheres(pl.home_pose))))

    with open(OUT, "w") as f:
        f.write("# GENERATED by scripts/bake_self_model.py — do not hand-edit.\n"
                "# cuRobo's collision spheres keyed by TF frame: [x, y, z, r] in\n"
                "# that frame. Arm links = cuRobo link frames (identical to the\n"
                "# ros2_kortex URDF); the gripper is in end_effector_link.\n")
        yaml.safe_dump({"source": os.path.basename(robot_yaml),
                        "spheres": {k: [[round(float(x), 5) for x in row] for row in v]
                                    for k, v in model.items()}},
                       f, default_flow_style=None, sort_keys=False)
    print("wrote %s: %d spheres over %d frames (gripper rigidity spread %.2e m)"
          % (OUT, total, len(model), spread))


if __name__ == "__main__":
    main()
